name: audio_classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pysoundfile
  - libvorbis
  - librosa
  - datasets
  - torchaudio
  - pip:
    - speechbrain