name: audio_classifier
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pysoundfile
  - libvorbis
  - librosa
  - datasets
  - matplotlib
  - numpy 
  - kaggle 
  - io
# --- PyTorch Packages ---
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=11.8
  - pip:
    - speechbrain